### ISSUE TITLE
Debugger entered--Lisp error: (file-missing "Cannot open load file" "没有那个文件或目录" "core-autoloads")

### ISSUE THREAD

**Issue by terryzhouke** [LdBeth/InfernoEmacs#1]
Debugger entered--Lisp error: (file-missing "Cannot open load file" "没有那个文件或目录" "core-autoloads")

(use-package core-autoloads
  :load-path "/core")

这部分没有起作用奇怪了

**Comment by matchcase** [comment]
The use-package for core-autoloads in pkgs.el should have a ":commands R" added to enable relative paths. Same for spacemacs-theme-autoloads

**Comment by LdBeth** [comment]
因为要手动生成 core-autoloads 文件

```
(make-directory-autoloads "~/.emacs.d/core" "~/.emacs.d/core/core-autoloads.el")
``` 

`spacemacs-theme-autoloads` 原理同样。

我没有设计成 clone 下来就能运行，是故意的。

**Comment by matchcase** [comment]
@LdBeth 请尝试将此添加到 pkgs.el
```lisp
(use-package core-autoloads
  :commands R
  :load-path "core/")
  ```
  &
  ```lisp
  (use-package spacemacs-theme-autoloads
  :commands R
  :load-path "core/spacemacs-theme/"
  :config
  (load-theme 'spacemacs-dark t)
  (load-theme 'spacemacs-light t t))
  ```

**Comment by LdBeth** [comment]
不需要 relative path，本来这就是一个 hack。
你对 `:commands` 作用的理解也是错的
